-- ============================================================
-- LokYatra: Full description update for all 40 heritage sites
-- ShortDescription, HistoricalSignificance, CulturalImportance
-- ============================================================

-- ID 1: Pashupatinath Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A sacred Hindu temple complex on the banks of the Bagmati River, dedicated to Lord Pashupati — a form of Shiva and the national deity of Nepal. The sprawling precinct contains over 500 temples, shrines, ashrams, and cremation ghats, with the main golden-roofed pagoda at its centre. Non-Hindu visitors may observe from the eastern bank and the hillside viewpoints above.',
  "HistoricalSignificance" = 'The site dates to at least the 5th century CE; the main temple was built in 1692 by King Bhupatindra Malla of Bhaktapur. Successive Malla and Shah dynasty rulers added gilded roofs, silver doors, and subsidiary shrines across the 246-hectare complex. The Pashupati Kshetra (sacred zone) is believed to have been a place of Shiva worship for over 2,000 years, with references in scriptures predating the current structure. UNESCO inscribed it as part of the Kathmandu Valley World Heritage Site in 1979.',
  "CulturalImportance" = 'Pashupatinath is the most sacred Hindu temple in Nepal and one of the most revered Shiva shrines in the world. Every year during Maha Shivaratri, over a million pilgrims arrive from Nepal and India. The Arya Ghat cremation ground on the Bagmati riverbank is one of the holiest sites for Hindu cremation rites — dying within the Pashupati Kshetra is believed to grant moksha (liberation). Hundreds of resident sadhus live in ashrams within the complex, and the eternal flame at the inner sanctum is said to have burned without interruption for centuries.'
WHERE "Id" = 1;

-- ID 2: Swayambhunath Stupa
UPDATE "CulturalSites" SET
  "ShortDescription" = 'An ancient Buddhist and Hindu sacred complex perched on a forested hill in western Kathmandu, crowned by a gleaming white stupa with the all-seeing eyes of the Buddha on all four sides. One of the oldest religious sites in Nepal, it is reached by climbing 365 stone steps lined with carved animals and spinning prayer wheels. The hilltop offers sweeping views across the Kathmandu Valley.',
  "HistoricalSignificance" = 'Buddhist chronicles place the site''s origin over 2,500 years ago, with the hill itself believed to have risen miraculously from a primordial lake that once filled the Kathmandu Valley. The stupa was enlarged by King Vrsadeva in the 5th century CE and received continuous patronage from Licchavi and Malla rulers. Emperor Ashoka is traditionally credited with a visit in the 3rd century BCE. The site is inscribed as part of the Kathmandu Valley UNESCO World Heritage Site (1979) and is one of the most complete early Vajrayana Buddhist complexes in existence.',
  "CulturalImportance" = 'Swayambhunath is sacred to both Newar Buddhists and Hindus, exemplifying the syncretic religious culture of the Kathmandu Valley. The 108 prayer wheels around the stupa are spun clockwise by thousands of daily worshippers. The site hosts shrines to Saraswati (particularly popular with students before exams), Harati (goddess of smallpox and children), and dozens of smaller deities. The resident monkey population has earned it the nickname "Monkey Temple" among international visitors, though Nepalis consider this an irreverent label for a profoundly sacred place.'
WHERE "Id" = 2;

-- ID 3: Boudhanath Stupa
UPDATE "CulturalSites" SET
  "ShortDescription" = 'One of the largest Buddhist stupas in the world, rising 36 metres above the flat Kathmandu Valley with the all-seeing eyes of the Buddha gazing in all four directions. A focal point of Tibetan Buddhism in Nepal, Boudhanath is surrounded by over 50 Tibetan monasteries and is the heart of Nepal''s Tibetan exile community. The evening kora — the circumambulation walk — draws hundreds of monks and laypeople daily.',
  "HistoricalSignificance" = 'The stupa was built around the 5th century CE on an ancient trade route between Nepal and Tibet, though Tibetan texts attribute it to much earlier origins. The site gained its greatest significance after the Tibetan diaspora of the 1950s, when thousands of refugees settled nearby and built dozens of monasteries. The upper spire was dislodged by the 2015 Gorkha earthquake; restoration was completed in 2016 in a ceremony attended by thousands of monks. Boudhanath is inscribed as part of the Kathmandu Valley UNESCO World Heritage Site (1979).',
  "CulturalImportance" = 'Boudhanath is the most important Tibetan Buddhist shrine outside Tibet and a living centre of Vajrayana Buddhist practice. The surrounding streets are lined with monasteries, thangka painting workshops, meditation centres, and Buddhist bookshops. On full moon days and during Losar (Tibetan New Year), the kora becomes a river of hundreds of monks in burgundy robes. The stupa''s mandala form — representing the entire Buddhist cosmos — makes the act of circumambulating it symbolically equivalent to a journey through the universe.'
WHERE "Id" = 3;

-- ID 4: Bhaktapur Durbar Square
UPDATE "CulturalSites" SET
  "ShortDescription" = 'The best-preserved medieval royal plaza in Nepal, set in the heart of Bhaktapur — the "City of Devotees" — with an extraordinary collection of palaces, pagoda temples, and carved courtyards built during the Malla dynasty. The 55-Window Palace, the five-storey Nyatapola Temple, and the intricately carved Peacock Window are considered masterpieces of Newar art. A living city rather than a dead museum, Bhaktapur''s streets still follow ancient occupational and religious traditions.',
  "HistoricalSignificance" = 'Bhaktapur was founded in the 12th century CE by King Ananda Malla and served as the capital of a unified Malla kingdom before the valley split into three city-states. From 1482 to 1769, it was the independent Malla capital, reaching its artistic and architectural peak under King Bhupatindra Malla (r. 1696–1722), who built the 55-Window Palace and oversaw major expansions. Conquered by Prithvi Narayan Shah in 1769, it declined in political importance but retained its cultural identity. The city sustained heavy damage in the 2015 earthquake but has undergone extensive restoration. Inscribed as UNESCO World Heritage Site in 1979.',
  "CulturalImportance" = 'Bhaktapur is one of the most intact medieval urban environments in Asia. The Newar community maintains traditional caste-based occupations — potters in Pottery Square, weavers, metalworkers, and woodcarvers — in the same neighbourhoods they have occupied for centuries. The city is famous for Juju Dhau (the King of Yoghurts), its own distinct cuisine, and the Bisket Jatra festival — Nepal''s most dramatic New Year celebration. Foreign visitors pay an entry fee that funds conservation work, making Bhaktapur a successful model of heritage tourism.'
WHERE "Id" = 4;

-- ID 5: Patan Durbar Square
UPDATE "CulturalSites" SET
  "ShortDescription" = 'The royal palace square at the heart of Lalitpur (Patan — City of Fine Arts), containing some of the finest Newar architecture and sculpture in the world. The ornate Golden Gate, Krishna Mandir, and Vishwanath Temple surround a central courtyard that represents the peak of medieval Newar civic design. The adjacent Patan Museum is considered one of the finest museums in South Asia.',
  "HistoricalSignificance" = 'Patan is one of the oldest continuously inhabited cities in Nepal. Legend attributes its founding to Emperor Ashoka in the 3rd century BCE, who is said to have erected the four Ashoka Stupas at the city''s cardinal points — three of which still stand. The city was the capital of an independent Malla principality from 1482 to 1769, when it was conquered by Prithvi Narayan Shah. The Royal Palace was progressively built from the 14th to 18th centuries and restored through a Nepal-Austria joint heritage project in the 20th century. Inscribed as UNESCO World Heritage Site in 1979.',
  "CulturalImportance" = 'Patan has been the artistic capital of the Kathmandu Valley for over a millennium. Its Newar craftsmen — particularly the Shakya community — are renowned throughout the Himalayan Buddhist world for bronze casting, repoussé metalwork, stone sculpture, and wood carving. Craftsmen from Patan were commissioned to build temples and cast statues in Tibet, China, and Bhutan. The city''s bahals (Buddhist monastery courtyards) are among the most important centres of Newar Buddhism, with living communities maintaining ritual traditions unchanged for centuries. Rato Machhindranath Jatra — the world''s longest chariot festival — originates in Patan.'
WHERE "Id" = 5;

-- ID 6: Kathmandu Durbar Square
UPDATE "CulturalSites" SET
  "ShortDescription" = 'The historic royal palace complex at the heart of old Kathmandu, known as Hanuman Dhoka Durbar Square, containing palaces, temples, and courtyards built across five centuries of Malla and early Shah rule. The Taleju Temple, Kumari Ghar (home of the living goddess), and the Hanuman Dhoka Palace Museum are the principal highlights. The square remains the ceremonial centre of the Nepali capital.',
  "HistoricalSignificance" = 'The palace complex was built progressively from the 12th to 18th centuries by successive Malla kings of Kantipur. After Prithvi Narayan Shah conquered Kathmandu in 1769, he continued to use Hanuman Dhoka as his seat until the new palace was built. The Taleju Temple (built 1564) was at the time of construction the tallest structure in the valley — a deliberate statement of royal power. The 2015 earthquake damaged several structures within the square, including the Kasthamandap (from which Kathmandu takes its name), which has since been rebuilt. Inscribed as UNESCO World Heritage Site in 1979.',
  "CulturalImportance" = 'Kathmandu Durbar Square remains the spiritual and ceremonial centre of the capital. The living goddess Kumari resides in the adjacent Kumari Ghar and makes rare public appearances from her carved window. The square is the main gathering point for Indra Jatra — the annual festival when the Kumari is taken through the old city in a chariot procession and the head of state receives her blessing. The Hanuman statue at the main gate has been wrapped in red cloth for so long that its original form is no longer visible beneath the layers of sindoor and offerings.'
WHERE "Id" = 6;

-- ID 7: Lumbini
UPDATE "CulturalSites" SET
  "ShortDescription" = 'The birthplace of Siddhartha Gautama — the historical Buddha — in the Terai plains of southern Nepal, making it one of the most sacred pilgrimage destinations for the world''s 500 million Buddhists. The Maya Devi Temple marks the precise spot of the birth, confirmed by an ancient Ashokan pillar inscription and a Marker Stone found beneath the temple. An international peace garden surrounds the site, with monasteries built by Buddhist nations from around the world.',
  "HistoricalSignificance" = 'Siddhartha Gautama was born here around 563 BCE (traditional date) to Queen Maya Devi of the Shakya clan. Emperor Ashoka visited in 249 BCE and erected a pillar bearing the inscription "Here the Buddha was born" — still standing today, cracked by a 14th-century lightning strike. The site was rediscovered in 1896 by archaeologist Alois Führer after centuries of neglect. Excavations since the 1990s under the Maya Devi Temple have revealed building foundations dating to the 3rd century BCE, corroborating the Ashokan record. UNESCO inscribed Lumbini as a World Heritage Site in 1997.',
  "CulturalImportance" = 'Lumbini holds a significance for Buddhists equivalent to Jerusalem for Christians or Mecca for Muslims. The sacred garden is being developed into a major international pilgrimage and peace site by the Lumbini Development Trust, with over 20 monasteries from different Buddhist traditions already built in the monastic zone. The Eternal Peace Flame near the Maya Devi Temple has burned without interruption since 1986. Pilgrims from Sri Lanka, Japan, Korea, China, Thailand, Myanmar, and Tibet all maintain active presences in the complex, making Lumbini a rare gathering point for the full diversity of world Buddhism.'
WHERE "Id" = 7;

-- ID 8: Changu Narayan Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'Nepal''s oldest standing temple, dedicated to Lord Vishnu in his Narayan form, perched on a forested hilltop east of Bhaktapur with panoramic valley views. The complex is extraordinary for the density and quality of its 4th–9th century CE stone sculptures, considered among the finest early Nepalese art in existence. The site also preserves the oldest stone inscription in Nepal, dating to 464 CE.',
  "HistoricalSignificance" = 'The original temple is believed to have been built in the 4th century CE during the Licchavi period — making it the oldest verifiable temple structure in Nepal. The 464 CE inscription of King Manadeva records military victories and the construction of the temple, providing one of the earliest firm dates in Nepali history. The temple was rebuilt and expanded by successive Licchavi, Malla, and Shah kings. It sustained damage in the 2015 earthquake, with several subsidiary shrines collapsing, but the main temple structure was preserved. Inscribed as UNESCO World Heritage Site in 1979.',
  "CulturalImportance" = 'Changu Narayan is one of the four Char Narayan Vishnu shrines of the Kathmandu Valley and is considered especially auspicious for Vaishnava worship. The stone sculptures within the complex — including the Vishnu Vikrantha striding across the three worlds and the Vishwaroopa multi-headed form — are studied by art historians as the definitive examples of early Nepalese sculpture. The hillside village of Changu maintains traditional Newar life including pottery, thangka painting, and woodcarving, providing an authentic cultural experience alongside the ancient temple.'
WHERE "Id" = 8;

-- ID 9: Manakamana Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A beloved Hindu temple dedicated to Goddess Bhagwati (Manakamana — "Wish of the Heart") at 1,302 metres on a ridge in Gorkha district, reached by Nepal''s first cable car over dramatic valley gorges. The goddess is believed to fulfil the heartfelt wishes of all who come to pray. Animal sacrifice remains central to the pilgrimage ritual, and the views of the Annapurna and Manaslu ranges on clear days are spectacular.',
  "HistoricalSignificance" = 'The temple was established in the 17th century CE and is strongly associated with the Gorkha Shah dynasty — the royal family who unified Nepal considered Manakamana one of their protective goddesses. Legend holds that a Magar holy man named Lakhan Thapa first received a vision of the goddess at this site. For most of its history, reaching the temple required a three-hour climb on foot; the cable car, built with Austrian technology, opened in 1998 and transformed access to the site. Today it is one of the most-visited temples in Nepal.',
  "CulturalImportance" = 'Manakamana is deeply embedded in the religious culture of central and western Nepal. Pilgrims come for every significant life event — marriage, new births, new business ventures, exam success, and recovery from illness — to seek the goddess''s blessing. The weekly crowds on auspicious days, the sound of bells and drums, the smell of incense and sacrificial fires, and the backdrop of the Himalaya create an atmosphere of intense popular devotion. The cable car journey itself — swinging over deep forested gorges — has become an experience visitors describe as transformative.'
WHERE "Id" = 9;

-- ID 10: Muktinath Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A supremely sacred temple complex at 3,710 metres in the Mustang district, revered by both Hindus as one of Vishnu''s 108 Divya Desams and by Tibetan Buddhists as the site where Guru Rinpoche achieved immortality. The 108 bull-headed stone water spouts, natural eternal flames burning beside water springs, and the high-altitude Himalayan setting make Muktinath one of the most otherworldly religious sites in the world.',
  "HistoricalSignificance" = 'Muktinath has been a pilgrimage site for thousands of years, situated on the ancient salt trade route between Nepal and Tibet. Hindu texts including the Vishnu Purana and the Devi Bhagavata identify it as one of the most sacred Vishnu sites. Tibetan Buddhist tradition records that Padmasambhava (Guru Rinpoche) performed longevity practices in the caves here in the 8th century CE. The Shah dynasty gave the Vishnu temple royal patronage, adding infrastructure for pilgrims. The sacred Saligram fossils (ammonites) found in the nearby Kali Gandaki riverbed are among the most sought-after Hindu sacred objects in South Asia.',
  "CulturalImportance" = 'Muktinath is one of the rarest religious sites on earth — a place where two entirely different faith traditions converge on the same sacred ground, each finding their own deity and narrative present. Hindus perform ritual bathing under the 108 spouts to wash away sin and earn liberation (mukti). Tibetan Buddhist pilgrims circumambulate the complex and visit the Jwala Devi (eternal flame) shrine. The altitude, remoteness, and the extraordinary physical phenomena of flame-beside-water create an experience of sacredness that pilgrims consistently describe as unlike any other.'
WHERE "Id" = 10;

-- ID 21: Taleju Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A magnificent three-storey pagoda temple dedicated to the royal goddess Taleju Bhawani, built in 1564 by King Mahendra Malla within the Kathmandu Durbar Square complex. At the time of its construction it was the tallest structure in the valley, a deliberate symbol of royal power and devotion. The temple is open to the public only once a year during Dashain festival; for the rest of the year only hereditary priests may enter.',
  "HistoricalSignificance" = 'Taleju Bhawani was brought from South India to the Kathmandu Valley by the Malla kings in the 14th century and installed as the state deity across all three city-states. The Kathmandu Taleju Temple was built in 1564 CE, the Bhaktapur Taleju Temple in 1553, and the Patan Taleju Temple in 1667. The goddess is connected to the Kumari tradition — legend holds that Taleju agreed to return as the living goddess Kumari after a king violated the secrecy of her nightly teachings. The temple survived the 2015 earthquake with minor damage and has been repaired.',
  "CulturalImportance" = 'Taleju Bhawani is considered the royal goddess of Nepal, the divine legitimiser of kingship. Even after Nepal became a republic in 2008, the Taleju traditions continue under state patronage. The annual Dashain festival opening of the Taleju Temple — when thousands queue for a glimpse inside — is one of the most anticipated religious events in the capital''s calendar. The temple''s dramatic height and its restricted access have given it an aura of sacred power that no amount of tourism has diminished.'
WHERE "Id" = 21;

-- ID 22: Patan Museum
UPDATE "CulturalSites" SET
  "ShortDescription" = 'One of the finest museums in South Asia, housed within the beautifully restored 17th-century Malla royal palace on the eastern side of Patan Durbar Square. The permanent collection presents over 1,500 pieces of Hindu and Buddhist sacred art in their cultural and ritual context. The museum building itself — its carved courtyards, gilded doorways, and stone fountains — is as important as the objects displayed within it.',
  "HistoricalSignificance" = 'The royal palace building dates to the 17th century Malla period and was the seat of the Patan kings until the Shah conquest of 1769. The palace was later used for various administrative purposes before being identified as a candidate for museum use. A twenty-year joint Nepal-Austria conservation and museum development project, completed in 1997, transformed the derelict palace into an internationally acclaimed museum while preserving all original architectural elements. The project became a model for adaptive reuse of heritage buildings across South Asia.',
  "CulturalImportance" = 'The Patan Museum is exceptional for presenting sacred art not as aesthetic objects isolated from meaning but within the context of the living religious traditions that created them. Interpretive panels explain how each piece was used — in processions, in daily puja, in royal ceremonies — making the collection accessible to visitors with no prior knowledge of Nepali art. The museum''s gift shop supports local craftspeople, and its conservation laboratory trains the next generation of Nepali heritage professionals. Entry to the museum includes access to the palace courtyards, which remain active pilgrimage points.'
WHERE "Id" = 22;

-- ID 23: National Museum of Nepal
UPDATE "CulturalSites" SET
  "ShortDescription" = 'Nepal''s largest and oldest museum, located in the Chhauni area of Kathmandu, housing collections spanning prehistory through the modern era across art, natural history, arms and armour, and Buddhist and Hindu artefacts. Particularly notable for its Licchavi-period stone sculptures and its collection of traditional Nepali weapons and military objects. The museum serves as the primary national repository for rescued and donated heritage objects.',
  "HistoricalSignificance" = 'Established in 1928 by Prime Minister Chandra Shumsher Rana in a building originally constructed as an armoury, the museum was Nepal''s first public institution dedicated to preserving national heritage. The collection has grown through acquisition, donation, and recovery of objects from the illegal antiquities trade. Significant pieces entered the collection after the 2015 earthquake when families donated objects too fragile to keep in damaged buildings. The museum collaborates with international institutions on conservation and research.',
  "CulturalImportance" = 'The National Museum preserves the full breadth of Nepal''s material heritage — from all regions, ethnic communities, and religious traditions. The stone sculpture gallery contains Licchavi-period masterpieces that chart the development of a distinctly Nepali artistic tradition independent of Indian models. The arms gallery documents the Gorkha military tradition that made Nepali soldiers (the Gurkhas) famous worldwide. The natural history section introduces visitors to Nepal''s extraordinary biodiversity — a country that contains five climatic zones and some of the world''s highest biodiversity concentrations in a territory the size of England.'
WHERE "Id" = 23;

-- ID 24: Pasupatinath Temple (second entry — covers the broader temple area/ghats)
UPDATE "CulturalSites" SET
  "ShortDescription" = 'The broader Pashupatinath sacred precinct encompassing the main temple complex, subsidiary shrines, riverside ghats, and the forests of the Mrigasthali deer park on the opposite bank of the Bagmati. Home to hundreds of resident sadhus and the site of continuous religious activity from dawn to late evening every day of the year.',
  "HistoricalSignificance" = 'Pashupatinath Temple is one of the four most important Shaiva pilgrimage sites in South Asia, alongside Varanasi, Rameshwaram, and Kedarnath. The 246-hectare complex contains 518 subsidiary temples and shrines accumulated over 1,500 years of royal patronage. The present main temple structure dates to 1692 CE (built by King Bhupatindra Malla) but stands on foundations of much older worship going back at least to the 5th century CE. UNESCO World Heritage Site since 1979.',
  "CulturalImportance" = 'This is the spiritual heart of Nepal and the most sacred site in Nepali Hinduism. The Pashupati Area Development Trust manages the complex and its endowment, which supports hospitals, schools, and charitable works for pilgrims. During Maha Shivaratri, over a million devotees descend on the complex in one of South Asia''s largest religious gatherings. The resident sadhus — many of them pilgrims from India who have made the complex their permanent home — are a constant visible presence of living renunciation within the busiest shrine in the country.'
WHERE "Id" = 24;

-- ID 25: Golden Temple Patan
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A magnificently gilded Buddhist monastery (Hiranya Varna Mahavihar — Golden Coloured Monastery) tucked into a narrow street north of Patan Durbar Square, its ornate gold repoussé facade hidden behind an unassuming entrance. Every surface of the main shrine building is covered in gleaming metalwork depicting the life of the Buddha and guardian deities. An active monastery still managed by the hereditary Shakya community.',
  "HistoricalSignificance" = 'Founded in the 12th century CE by King Bhaskar Varma, the monastery has been continuously embellished across nine centuries of Shakya community patronage. The current golden facade represents layers of artistic addition spanning the 12th to 20th centuries. The Shakya craftsmen who created the metalwork belong to the same caste group as the historical Buddha Siddhartha Gautama — making their custodianship of the monastery a direct continuity with the origins of Buddhism. The monastery survived the 2015 earthquake with minimal structural damage.',
  "CulturalImportance" = 'The Golden Temple is a functioning monastic institution, not merely a heritage monument. Daily and seasonal rituals are performed by resident monks and the Shakya community. Young boys from Shakya families are required to spend a period in residence as novice monks — a tradition continuing for over a thousand years. The courtyard atmosphere — intense sacredness enclosed by the mundane city just outside the door — is characteristic of Patan''s living Buddhist culture. A sacred white rat roams freely within the complex and is revered as a representative of Ganesh.'
WHERE "Id" = 25;

-- ID 26: Mahaboudha Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A unique North Indian shikhara-style tower temple built entirely of terracotta bricks, each one bearing the image of the Buddha — so the whole structure is a continuous act of devotion multiplied across thousands of surfaces. Inspired by the Mahabodhi Temple in Bodh Gaya (India), it was built in the 16th century by a local Patan architect-pilgrim. The temple is squeezed into a narrow courtyard in the old city, its full height best appreciated by pressing against the opposite wall.',
  "HistoricalSignificance" = 'Built in the 16th century CE by Abhaya Raj, a Patan resident who spent years in India studying the Mahabodhi Temple before recreating it at home. The shikhara (tapering tower) style is rare in Nepal, whose architecture is dominated by the Newar pagoda form — making Mahabouddha an architectural anomaly and a testament to the cross-cultural exchange of Buddhist traditions. The 2015 earthquake badly damaged the structure; it was meticulously dismantled brick by brick, numbered, and rebuilt. The surplus bricks from the restoration were used to construct a smaller Maya Devi shrine beside it.',
  "CulturalImportance" = 'Mahabouddha embodies the Buddhist tradition of pilgrimage replication — recreating a sacred site so that those unable to travel to the original can gain merit through proximity to its form. The ten thousand Buddha images on its surface make it a material mandala, a complete expression of the Buddhist universe in a single tower. For the craftsmen who built and have since maintained it, the temple is both a religious act and a professional legacy — the finest example of terracotta work in the Kathmandu Valley.'
WHERE "Id" = 26;

-- ID 27: Bindabasini Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'The most important Hindu temple in Pokhara, dedicated to Goddess Bhagwati (an aspect of Durga), standing on a prominent hill in the old bazaar with panoramic views of the Pokhara valley, Phewa Lake, and the Annapurna Himalayan range. A centre of daily devotion for the city''s residents, especially on Tuesdays and Saturdays when crowds of worshippers bring flowers, incense, and offerings.',
  "HistoricalSignificance" = 'The temple has been the principal religious site of Pokhara for several centuries, closely associated with the ruling family of the Kaski kingdom of which Pokhara was the main city. The goddess Bindabasini served as the protective deity for the merchant communities who traded along the Himalayan salt routes between Tibet and the Indian plains. The current temple structure dates to the 19th century, though worship at this hill predates the present building. The temple became more widely accessible after the Pokhara-Kathmandu road was built in the 1970s.',
  "CulturalImportance" = 'Bindabasini is not merely a landmark but the living spiritual centre of Pokhara. For the Gurung, Magar, Brahmin, and Chhetri communities of the region, the goddess is an active presence in daily life, petitioned for health, safe travel, children, and prosperity. The weekly Tuesdays and Saturdays see hundreds of devotees climbing the hill before dawn, and the major festivals of Dashain and Tihar transform the temple complex into a focal point for the entire city. The hilltop location gives the temple a commanding presence over the city below.'
WHERE "Id" = 27;

-- ID 28: Tal Barahi Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A two-storey pagoda temple dedicated to Goddess Barahi (a tantric form of Durga) situated on a small forested island in the middle of Phewa Lake, Pokhara. Reached exclusively by wooden rowboat from the lakeside ghats, the journey across the water with the Annapurna range reflected in the lake is one of Nepal''s most serene pilgrimage experiences. The temple island is one of Pokhara''s most photographed and visited sites.',
  "HistoricalSignificance" = 'The Barahi Temple was established by the ruling family of the Kaski kingdom as a protective deity for the Pokhara region. The current temple structure dates to the 20th century, though the island has been a sacred site for several centuries. The goddess Barahi is believed to have appeared to a local devotee in a vision and requested a temple on the lake island. The Pokhara-Phewa Lake area gained international tourist significance from the 1970s, which dramatically increased the temple''s visitors while also maintaining its religious character.',
  "CulturalImportance" = 'Tal Barahi is inseparable from the identity of Pokhara — the image of the white-and-red temple on the lake with the snow mountains beyond has become the defining visual symbol of the city. The boat journey across Phewa Lake is itself a meditative act that separates the commercial world of the lakeside from the sacred space of the island. On auspicious Saturdays, families queue at the ghats from early morning for the short boat ride to make offerings to the goddess. The lake''s waters are considered sacred and bathing at the island shores carries religious merit.'
WHERE "Id" = 28;

-- ID 29: Kathesimbhu Stupa
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A small but deeply revered Buddhist stupa in the Thamel neighbourhood of Kathmandu, built as a replica of Swayambhunath for those unable to make the steep climb to the hilltop stupa. The all-seeing eyes of the Buddha and the surrounding prayer wheels, chaityas, and small shrines create a complete devotional space within the busy city. Despite the commercialisation of Thamel around it, the stupa remains an active neighbourhood shrine.',
  "HistoricalSignificance" = 'Built in the 17th century CE on the initiative of elderly and infirm members of the Thamel Newar Buddhist community who could not manage the climb to Swayambhunath. Buddhist tradition holds that circumambulating Kathesimbhu confers the same merit as visiting the original hill-top stupa — a compassionate adaptation of sacred geography to human physical limitation. The surrounding area was historically a dense Newar Buddhist neighbourhood before the tourist trade transformed Thamel''s character from the 1970s onwards.',
  "CulturalImportance" = 'Kathesimbhu demonstrates how Buddhist practice in Nepal continually adapts to serve its community — creating accessible entry points to merit and devotion for all, regardless of physical ability or age. The stupa is the surviving anchor of Buddhist community life in an area that has otherwise been largely commercialised. The 108 prayer wheels around the base are spun by passing worshippers throughout the day, and the resident pigeons that gather on the terraces are considered auspicious.'
WHERE "Id" = 29;

-- ID 30: Charumati Stupa
UPDATE "CulturalSites" SET
  "ShortDescription" = 'One of the oldest stupas in the Kathmandu Valley, located in the Chabahil neighbourhood, traditionally associated with Charumati — the daughter of Emperor Ashoka — who is said to have settled in Nepal after marrying a Nepali nobleman. One of four Ashokan-era stupas believed to mark the boundaries of the ancient sacred zone of the valley. A quiet, non-commercial pilgrimage site away from the main tourist trail.',
  "HistoricalSignificance" = 'According to the Vamsavali (royal chronicles of Nepal), Emperor Ashoka visited the Kathmandu Valley in the 3rd century BCE and his daughter Charumati established a stupa and monastery at Chabahil. Archaeological evidence of Buddhist activity in the area dating to the Ashokan period supports the broad tradition, if not the specific details. The stupa has been rebuilt and renovated multiple times across its 2,300-year history. The Chabahil area contains another ancient stupa (Dhando Chaitya) nearby, forming a cluster of early Buddhist monuments.',
  "CulturalImportance" = 'Charumati Stupa represents the deepest layer of Buddhism in Nepal — a tradition that predates even the Licchavi kingdom and connects Nepal to the earliest history of the faith. Its quiet, unrestored atmosphere makes it a valuable counterpoint to the heavily visited major stupas. For devotees and scholars alike, the stupa provides a tangible link to the period when Buddhism first arrived in the Kathmandu Valley through the channels of Ashoka''s empire.'
WHERE "Id" = 30;

-- ID 31: Indreshwar Mahadev Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'Believed to be the oldest surviving triple-roofed pagoda temple in Nepal, standing at the sacred riverside confluence of Panauti town in Kavrepalanchok district since 1294 CE. The woodwork, stone sculpture, and architectural proportions of this Shiva temple are considered masterpieces of medieval Newar craft. Panauti''s preserved medieval townscape — stone lanes, stepped fountains, and intact courtyards — provides the perfect setting.',
  "HistoricalSignificance" = 'The temple is dated to 1294 CE by inscription, making it the oldest verifiably dated standing pagoda temple in Nepal — surviving six centuries including multiple major earthquakes. The 1988 Udaipur earthquake that devastated much of the surrounding Kavrepalanchok district left the main temple structurally intact. The 2015 Gorkha earthquake caused damage to subsidiary shrines but the main triple-roofed tower survived again. The temple has been the subject of conservation research by the German Technical Cooperation and other international heritage organisations.',
  "CulturalImportance" = 'Panauti''s location at the trisuli (triple river confluence of the Roshi and Punyamati rivers) is considered highly sacred in the Hindu tradition — bathing at the confluence washes away sin. The Makar Mela festival held every 12 years at Panauti draws hundreds of thousands of pilgrims. Panauti is also one of Nepal''s best-preserved medieval urban environments, giving the Indreshwar temple a context that the Kathmandu Valley''s more heavily visited sites have largely lost to modernisation and tourism pressure.'
WHERE "Id" = 31;

-- ID 32: Gorakhnath Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'An ancient cave temple dedicated to the Nath yogi Gorakhnath within the fortified Gorkha Durbar complex, the ancestral seat of the Shah dynasty who unified Nepal. The Gorkha Durbar sits dramatically on a ridge above Gorkha town, and the name "Gorkha" — which has given the world the word "Gurkha" — derives from this yogi patron. The complex offers outstanding views across the Himalayan foothills.',
  "HistoricalSignificance" = 'The Gorkha Durbar and Gorakhnath Temple were the political and spiritual centre of the small Gorkha kingdom before Prithvi Narayan Shah began his unification campaign in 1743. The Shah dynasty traced their legitimacy partly to the blessing of Gorakhnath — Prithvi Narayan Shah is said to have received a vision of the yogi that confirmed his mission. The Gorkha kingdom''s eventual success in uniting Nepal under a single crown transformed this small hill fort into the birthplace of the modern Nepali state. The fortified palace suffered damage in the 2015 earthquake but has been substantially repaired.',
  "CulturalImportance" = 'The Gorakhnath connection runs through all of Nepali military culture. The Nepali Army, the Indian Army''s Gurkha regiments, and the British Army''s Brigade of Gurkhas all trace their identity to the Gorkhali warriors who first united Nepal. The footprint of Gorakhnath — believed to be supernaturally pressed into rock within the temple — is one of the most sacred objects in the complex. Pilgrims from across the Nath tradition and from India visit the site, recognising it as one of the most important Gorakhnath shrines in the world.'
WHERE "Id" = 32;

-- ID 33: Halesi Mahadev
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A remarkable complex of sacred caves in Khotang district of eastern Nepal, simultaneously revered by Hindus as a major Shiva site, by Tibetan Buddhists as the cave where Guru Rinpoche achieved immortality, and by indigenous Rai and Limbu communities as an ancestral sacred space. This convergence of three distinct religious traditions at a single cave complex is unique in Nepal. The main cave is large enough to hold hundreds of worshippers and is entered through a natural rock arch.',
  "HistoricalSignificance" = 'The cave''s sanctity in the Tibetan Buddhist tradition stems from the tradition that Padmasambhava (Guru Rinpoche) performed longevity (amitayus) practices here in the 8th century CE, achieving a form of immortality at the site known to Tibetans as Maratika. Hindu texts identify the site with Shiva''s presence — a jyotirlinga equivalent, though not among the 12 canonical ones. Local Rai and Kirat shamanic traditions consider the cave an ancestral abode of spirits predating both Hindu and Buddhist influences. The caves have been a multi-faith pilgrimage site for at least a thousand years.',
  "CulturalImportance" = 'Halesi Mahadev exemplifies the religious syncretism at the heart of Nepali culture — the same physical space holds meaning for multiple faith traditions without conflict or competition. Major Hindu pilgrimage seasons and Tibetan Buddhist pilgrimage dates bring different communities to the same caves at different times. For Tibetan Buddhists worldwide, the Maratika caves are one of the most important pilgrimage sites outside Tibet. For eastern Nepal''s Rai and Limbu communities, the caves connect them to ancestral spiritual geography that predates any named religion.'
WHERE "Id" = 33;

-- ID 34: Kalinchowk Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A high-altitude temple dedicated to Goddess Kalinchowk Bhagwati (an aspect of Durga) at 3,842 metres on the Kalinchowk mountain ridge in Dolakha district. One of the highest Hindu temples in Nepal accessible by road and chairlift, it offers extraordinary views of the Langtang, Rolwaling, and Gaurishankar Himalayan ranges. The winter snowfields surrounding the temple add an atmosphere of supreme sacredness.',
  "HistoricalSignificance" = 'The Kalinchowk Bhagwati temple has been a pilgrimage destination for the communities of Dolakha and surrounding districts for centuries. The 2015 earthquake caused significant damage to Charikot town below but the mountain temple suffered less structural damage than the valley settlements. A chairlift installed in 2016 has made the summit accessible to pilgrims who previously faced a challenging high-altitude hike. The mountain''s sacred status predates any recorded history and is woven into the origin myths of the Tamang and Magar communities of the region.',
  "CulturalImportance" = 'Kalinchowk is one of the most visited winter pilgrimage sites in Nepal. The combination of extreme altitude, snowfields, and the fierce goddess creates a pilgrimage experience felt to be proportionally powerful — the hardship of the journey amplifies the devotional act. On auspicious days the mountain summit is crowded with families who have driven from Kathmandu and beyond. The snow-covered mountain gives the goddess an austere, powerful presence that reinforces her role as a force of nature as much as a personal deity.'
WHERE "Id" = 34;

-- ID 35: Swargadwari Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A sacred Hindu ashram and temple complex at 1,920 metres in Pyuthan district of western Nepal, believed to be the site where the sage Vedavyasa (author of the Mahabharata) meditated. The name means "Gate of Heaven" — dying near this site is believed to grant direct passage to heaven. The annual Swargadwari Mela pilgrimage festival draws hundreds of thousands of devotees from across western Nepal.',
  "HistoricalSignificance" = 'The ashram at Swargadwari was formally organised in the 19th century by a lineage of Vaishnava teachers who established the current temple complex and festival traditions. Religious activity at the hilltop is believed to be much older, with local traditions connecting the site to the Vedic period. The annual Mela festival (held in Baisakh — April/May) has grown progressively larger each decade and now ranks as one of the largest religious gatherings in Nepal outside the Kathmandu Valley. Road access from Pyuthan was completed in the 21st century, replacing the previously arduous foot journey.',
  "CulturalImportance" = 'Swargadwari is the spiritual centre of western Nepal''s mid-hill communities — for Pyuthan, Rolpa, Gulmi, Arghakhanchi, and surrounding districts, it carries the significance that Pashupatinath holds for Kathmandu. The festival brings together people of diverse ethnic backgrounds — Brahmin, Chhetri, Magar, and Tharu communities — in shared Vaishnava devotion. The resident sadhus perform continuous Vedic fire rituals (yajna) throughout the year, and the ashram maintains a tradition of free food (prasad) for all pilgrims regardless of caste or economic status.'
WHERE "Id" = 35;

-- ID 36: Rato Machhindranath Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'Home to Rato Machhindranath — the rain god and patron deity of the Kathmandu Valley — whose annual chariot festival (Rato Machhindranath Jatra) is believed to be the world''s longest chariot festival, lasting several months as a massive hand-built wooden chariot is pulled through the streets of Patan. The festival is an act of collective petition for adequate monsoon rains. The temple is located in the Lagankhel area of Patan.',
  "HistoricalSignificance" = 'Rato Machhindranath is a syncretic deity combining the Hindu Machhindranath with the Buddhist bodhisattva Avalokitesvara (Karunamaya). The chariot festival tradition is believed to date to the reign of the Licchavi king Narendra Deva in the 7th century CE, who brought the god''s idol from Assam (India) to end a drought. The annually rebuilt chariot — constructed without nails from fresh wood, bamboo, and sacred materials — represents an unbroken chain of craftsmanship traditions stretching back over a thousand years. The Bhoto Jatra ceremony that closes the festival was traditionally witnessed by the king of Nepal and is now presided over by the President.',
  "CulturalImportance" = 'The Jatra is a community festival in the fullest sense — every neighbourhood in Patan has a designated hereditary role in the festival''s organisation, construction, and completion. Thousands of volunteers pull the chariot ropes over months of processions through the streets. The festival''s agricultural basis — rain for the harvest — connects it directly to the survival of the farming communities who have celebrated it for fourteen centuries. Even as Patan has urbanised, the Jatra continues with the same ritual precision, a living expression of the city''s collective identity.'
WHERE "Id" = 36;

-- ID 37: Nuwakot Palace
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A historic seven-storey tower palace in Nuwakot district, one of the most strategically significant palaces in Nepali history — captured by Prithvi Narayan Shah in 1744 as his first major military victory on the road to unifying Nepal. The palace offers commanding views across the Trisuli valley and served as one of Prithvi Narayan Shah''s principal residences during the unification campaign. A rare example of a seven-storey Newar palace structure.',
  "HistoricalSignificance" = 'The capture of Nuwakot in 1744 gave Prithvi Narayan Shah control of the Trisuli valley trade route and access to the resources needed to continue his campaign. He issued the Dibya Upadesh (Divine Advice) — a political and moral treatise for the governance of Nepal — from Nuwakot, making it not only a military but an intellectual birthplace of the modern Nepali state. The palace was badly damaged in the 2015 earthquake and is undergoing restoration. The seven storeys, each serving a different function, represent the most ambitious Newar palace construction outside the Kathmandu Valley.',
  "CulturalImportance" = 'Nuwakot is essential to understanding the founding narrative of modern Nepal. Without the capture of Nuwakot, Prithvi Narayan Shah''s campaign might never have progressed. For Nepali students of history, the palace is where the abstract story of unification becomes physically real — a building you can walk through that still carries the atmosphere of its 18th-century purpose. The Dibya Upadesh issued here remains studied as a foundational political document, advising later generations on how to maintain Nepal''s sovereignty between the great powers of India and China.'
WHERE "Id" = 37;

-- ID 38: Bhimsen Temple Patan
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A prominent five-storey pagoda temple in Patan Durbar Square dedicated to Bhimsen — the mightiest of the Pandava brothers — who is uniquely worshipped in Nepal as the patron deity of merchants and traders. The temple''s ground floor was historically used as a commercial hall, physically integrating the sacred and economic in the manner characteristic of Newar urban life. Especially active on the first day of each month when traders bring offerings.',
  "HistoricalSignificance" = 'Built in 1682 CE during the Malla period, the Bhimsen Temple is one of the most prominent structures on Patan Durbar Square''s southern side. The cult of Bhimsen as merchant deity is a Newar innovation not found in Indian Hindu tradition — it evolved to meet the needs of Patan''s powerful trading community during the height of the trans-Himalayan trade. The lower hall of the temple functioned as a commercial space where merchants conducted business under divine protection, a practice that continued well into the modern period.',
  "CulturalImportance" = 'Bhimsen''s role as patron of commerce demonstrates how Nepal''s religious traditions adapted pan-South Asian mythological figures to serve local community needs. The temple is an active commercial prayer centre — Patan''s businesspeople visit regularly to seek divine backing for their ventures. The integration of trade and religion at Bhimsen Temple reflects the Newar community''s understanding that economic success is not separate from spiritual life but depends on maintaining right relationship with the divine forces that govern human affairs.'
WHERE "Id" = 38;

-- ID 39: Tribhuvan Museum
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A museum within the Hanuman Dhoka Palace complex dedicated to King Tribhuvan Bir Bikram Shah — the monarch who ended a century of Rana oligarchy and restored democratic rights to Nepal in 1951. The preserved royal apartments, personal objects, and the room where he sheltered anti-Rana leaders tell the story of a king who risked his throne to free his people. One of the most intimate and personally moving museums in Kathmandu.',
  "HistoricalSignificance" = 'King Tribhuvan (r. 1911–1955) was effectively powerless under the Rana prime ministers who ran Nepal as a hereditary oligarchy. In November 1950, he sought asylum in the Indian Embassy in Kathmandu with most of his family, flew to India, and triggered the political revolution that ended Rana rule and restored the monarchy''s active power. The museum, established after his death in 1955, preserves his personal rooms, furniture, books, and clothing in their original arrangement, creating an unusually intimate portrait of a historical figure. The 1979 UNESCO World Heritage inscription of Kathmandu Durbar Square includes the Hanuman Dhoka complex.',
  "CulturalImportance" = 'Tribhuvan is revered as Janata ke Pita — Father of the Nation — in Nepal, and his image appeared on Nepali currency for decades. The museum makes the democratic transition of 1951 concrete and personal: visitors see the actual living space of the man who chose political risk over royal comfort to serve his people. The story of asylum in an embassy, a flight to India, and the fall of a century-old oligarchy is one of the most dramatic episodes in modern Nepali history, and the museum gives it a human face and a physical location.'
WHERE "Id" = 39;

-- ID 40: Pashupatinath Ghats
UPDATE "CulturalSites" SET
  "ShortDescription" = 'The sacred cremation ghats along the Bagmati River at Pashupatinath, where Nepali Hindus have been cremated in open-air ceremonies for over a millennium. Watching a cremation here — public, communal, and spiritually integrated — is one of the most profound experiences available to a visitor in Nepal. The ghats extend for several hundred metres along the river, each section associated with specific ritual purposes, castes, and royal ceremonies.',
  "HistoricalSignificance" = 'The Pashupatinath cremation ghats have been in continuous use for at least 1,500 years, possibly much longer. The Arya Ghat on the southern bank is reserved for members of the royal family and high-caste Brahmins; the northern ghats serve the broader community. The Bagmati is considered equivalent in sanctity to the Ganges, and cremation on its banks is believed to guarantee liberation from the cycle of rebirth. Every day, multiple cremations take place simultaneously, maintaining an unbroken chain of ritual across the generations.',
  "CulturalImportance" = 'The Pashupatinath ghats embody a relationship with death unique among world cultures — open, communal, and spiritually matter-of-fact rather than hidden or sanitised. For Nepali Hindus, the ghats are not morbid but hopeful: the sacred river carries the soul toward liberation. For visitors, the experience consistently prompts deep reflection on mortality and the human community of grief. The sadhus who sit in meditation on the opposite bank, the family members sitting with their loved ones, the pilgrims bathing upstream — all exist simultaneously in a space where life and death are not opposed but continuous.'
WHERE "Id" = 40;

-- ID 41: Doleshwar Mahadev
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A Shiva temple in Suryabinayak, Bhaktapur district, holding the extraordinary distinction of being recognised as the mukha (face/head) of the Kedarnath Shiva shrine in the Himalayas of Uttarakhand, India. Since this recognition was formalised in 2009, Doleshwar has become an important destination for Indian pilgrims who add it to the Char Dham circuit. The quiet hillside temple sits amid the Suryabinayak forest with views across the valley.',
  "HistoricalSignificance" = 'In 2009, the Kedarnath Temple Trust and the Archaeological Survey of India formally recognised Doleshwar Mahadev as the face of the bull whose body parts became the Panch Kedar — the five sacred Shiva sites of Garhwal, India — based on Puranic textual evidence and local traditions maintained for centuries. This recognition transformed a previously quiet local temple into an internationally significant pilgrimage site virtually overnight. The temple''s connection to the Kedarnath mythology is recorded in ancient Puranic texts and was preserved in oral tradition by the local community until scholarly attention confirmed it.',
  "CulturalImportance" = 'Doleshwar Mahadev demonstrates how pilgrimage geography in Hinduism creates a unified sacred landscape across vast distances — a temple in the Bhaktapur hills is cosmologically connected to one of the most famous Himalayan shrines. The formal recognition by Kedarnath authorities brought thousands of Indian pilgrims to Nepal specifically to visit this site, creating new connections between Nepal and India''s Hindu communities. For local devotees, the recognition validated centuries of oral tradition and gave their neighbourhood temple a place in the all-India pilgrimage cosmography.'
WHERE "Id" = 41;

-- ID 42: Kumari Ghar
UPDATE "CulturalSites" SET
  "ShortDescription" = 'The palace of the Royal Kumari — a pre-pubescent girl from the Shakya Buddhist community who is selected through elaborate rituals to be the living incarnation of the goddess Taleju. The intricately carved three-storey Kumari Ghar was built in 1757 and is located beside Kathmandu Durbar Square. The Kumari appears at her carved wooden window on special occasions and is carried in a golden chariot through the old city during Indra Jatra.',
  "HistoricalSignificance" = 'The Royal Kumari institution is believed to date to the Malla period (15th–18th centuries) when the king required a living divine presence to legitimise his rule. The present Kumari Ghar was built in 1757 by Jaya Prakash Malla. The tradition survived the Shah conquest of 1769, the transition to a Hindu Kingdom under the Rana and Shah dynasties, and the declaration of a republic in 2008 — the Kumari now blesses the President rather than the king. The selection process, involving 32 physical perfections and psychological testing, is documented by the Guthi Sansthan (cultural foundation that manages the institution).',
  "CulturalImportance" = 'The Kumari tradition is one of the most extraordinary living religious practices in the world: a child who is simultaneously fully divine and fully human, revered as a goddess and then returned to ordinary life at puberty. Former Kumaris carry a lifelong social prestige and are sought after for blessings at community events. The institution has attracted both admiration for its preservation of ancient living tradition and human rights debate about childhood. The Kumari''s annual Indra Jatra chariot procession through the old city is one of the most visually spectacular events in Kathmandu''s festival calendar.'
WHERE "Id" = 42;

-- ID 43: Kopan Monastery
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A Tibetan Buddhist monastery on a peaceful forested hill north of Boudhanath, founded in 1969 by Lama Thubten Yeshe and Lama Zopa Rinpoche, which became in the 1970s a transformative bridge between traditional Tibetan Buddhism and Western spiritual seekers. Today it houses around 350 resident monks and continues to offer intensive meditation and Buddhist study courses to students from around the world. The hilltop views across the valley to Boudhanath Stupa are exceptional.',
  "HistoricalSignificance" = 'Kopan was established on land donated by a Tibetan nobleman in 1969. The first public meditation course, offered in 1971 to a handful of Western participants, launched a practice that grew to attract hundreds of applications from Europe, America, and Australia within a few years. The monastery became the seed institution of the Foundation for the Preservation of the Mahayana Tradition (FPMT), now one of the world''s largest Tibetan Buddhist organisations with over 160 centres in 40 countries. Both founding lamas were themselves Tibetan refugees who had fled the Chinese occupation of Tibet in 1959.',
  "CulturalImportance" = 'Kopan represents one of the most successful examples of traditional monastic Buddhism''s transmission to a global audience. The monastery maintains both a full traditional curriculum for Tibetan and Nepali monks and an intensive international programme for lay practitioners from dozens of countries. The hilltop location, with prayer flags and mountain views, creates an atmosphere that has been described by thousands of retreat participants as among the most conducive to meditation they have encountered anywhere in the world.'
WHERE "Id" = 43;

-- ID 44: Shechen Monastery
UPDATE "CulturalSites" SET
  "ShortDescription" = 'One of the most important Nyingma school Tibetan Buddhist monasteries in the world, rebuilt near Boudhanath in 1980 after its original in Kham, eastern Tibet was destroyed during the Cultural Revolution. Founded by Dilgo Khyentse Rinpoche — one of the most revered Tibetan Buddhist masters of the 20th century — the monastery preserves an ancient lineage of teaching, ritual, and sacred art. Traditional thangka paintings and a large Padmasambhava statue grace the main temple.',
  "HistoricalSignificance" = 'The original Shechen monastery in Kham was one of the six "mother monasteries" of the Nyingma school — the oldest school of Tibetan Buddhism — and one of the greatest centres of Buddhist scholarship in eastern Tibet before its destruction in the 1960s. Dilgo Khyentse Rinpoche, who had been a student at the original Shechen, chose the Boudhanath area for the rebuild in 1980 due to its established Tibetan community and the sacred presence of the great stupa. The monastery maintains a three-year retreat centre and traditional monastic schools for young monks.',
  "CulturalImportance" = 'Shechen represents the broader story of Tibetan Buddhism''s remarkable survival and global dissemination after the near-destruction of its home culture. The monastery is a living institution that preserves rare ritual traditions, sacred texts, and artistic styles of the Nyingma Kham lineage — some of which exist nowhere else outside its walls. The current head, Rabjam Rinpoche, continues the transmission of teachings from the original Shechen. International students from Europe, America, and Asia study here alongside Tibetan and Nepali monks, ensuring the tradition''s continuity.'
WHERE "Id" = 44;

-- ID 45: Phewa Lake Barahi Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'The iconic Barahi Temple on a small forested island in Phewa Lake, Pokhara, dedicated to Goddess Barahi — a tantric form of Durga believed to protect the Pokhara region. Reached by wooden rowboat from the lakeside ghats, the combination of the island setting, the lake reflections, and the Annapurna range in the background makes the approach one of Nepal''s most photographed and serene pilgrimage experiences.',
  "HistoricalSignificance" = 'The Barahi Temple was established by the ruling family of the Kaski kingdom, of which Pokhara was the principal city. The goddess Barahi is the traditional protective deity of the Pokhara valley. The current temple structure was rebuilt in the 20th century on the island that has been a sacred site for several centuries. Phewa Lake itself is believed to be sacred, and its waters are associated with the goddess''s presence. The development of Pokhara as an international tourist destination from the 1970s greatly increased the temple''s visibility but has not diminished its religious character.',
  "CulturalImportance" = 'Barahi Temple is central to Pokhara''s cultural identity. The image of the white temple on the lake with snow mountains behind has become the city''s defining symbol, reproduced in tourism materials worldwide. On auspicious Saturdays, families queue at the lakeside ghats from early morning for the short boat ride to offer prayers to the goddess. The boat journey itself — crossing the water toward the island temple, hearing the bells carried on the breeze — is one of those simple, unrepeatable experiences that visitors to Nepal consistently name as among their most memorable.'
WHERE "Id" = 45;

-- ID 46: Bikram Sambat Museum
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A museum in Bhaktapur documenting the Bikram Sambat (BS) calendar system — Nepal''s official civil calendar, which runs 56 years and 8.5 months ahead of the Gregorian calendar and governs the entire rhythm of Nepali religious, agricultural, and civic life. The museum also preserves artefacts from the Malla dynasty period and documents the cultural heritage of Bhaktapur across multiple centuries.',
  "HistoricalSignificance" = 'The Bikram Sambat era is named for the legendary King Vikramaditya of Ujjain, India, and its year 1 corresponds to 57 BCE in the Gregorian system — making the current year (2024 AD) BS 2081. Nepal is one of very few countries in the world to use a non-Gregorian calendar as its official civil calendar. The museum was established within the historic Bhaktapur palace complex to document this unique aspect of Nepali culture alongside the broader Malla heritage of the city.',
  "CulturalImportance" = 'The Bikram Sambat calendar is not merely an administrative system but the living framework of Nepali cultural life. All major festivals, agricultural seasons, wedding dates, and religious observances are calculated according to BS. Understanding the calendar system is essential to understanding why Nepal''s cultural calendar seems so different from the international norm — why New Year falls in April, why festival dates shift each year, and why Nepali people carry two mental calendars simultaneously. The museum makes this invisible cultural infrastructure visible to visitors.'
WHERE "Id" = 46;

-- ID 47: Lumbini Museum
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A museum within the Lumbini sacred garden preserving archaeological finds from the Lumbini area and providing essential historical context for the site''s extraordinary spiritual significance. The collection spans from the Mauryan period (3rd century BCE) through the medieval era, including terracotta figurines, coins, and architectural fragments. The museum bridges the gap between archaeological fact and living faith for the millions who visit the birthplace of the Buddha.',
  "HistoricalSignificance" = 'The Lumbini Museum was established by the Lumbini Development Trust to display and protect finds from ongoing excavations at the sacred garden. Key discoveries contextualised by the museum include the Marker Stone found beneath the Maya Devi Temple — confirming the precise spot of the Buddha''s birth — and the layers of building foundations showing continuous occupation and veneration of the site from the 3rd century BCE. International archaeological teams from Japan, Nepal, and other countries have contributed to the excavation record presented in the museum.',
  "CulturalImportance" = 'The Lumbini Museum serves pilgrims who arrive with faith and visitors who arrive with curiosity, providing each with what they need: the faithful receive historical confirmation of their tradition, the sceptical encounter evidence that gives the site''s claims credibility. For Buddhist pilgrims from Japan, Korea, Sri Lanka, and Thailand — nations where the historical Buddha can seem distant and legendary — the museum''s physical evidence of the actual birth site provides a profoundly concrete connection to the origins of their faith.'
WHERE "Id" = 47;

-- ID 48: Swayambhu Natural History Museum
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A natural history museum at the base of the Swayambhunath hill, operated by Tribhuvan University, documenting Nepal''s extraordinary biodiversity and geological history. Collections cover Nepal''s birds (over 900 species), mammals from tigers to snow leopards, butterflies, and geology including the formation of the Himalayas. An educational complement to the spiritual experience of the adjacent Swayambhunath complex.',
  "HistoricalSignificance" = 'Established in 1975 as part of Tribhuvan University''s Institute of Science and Technology, the museum was created to document and communicate Nepal''s natural heritage to both domestic students and international visitors. The museum''s geological exhibits track the 50-million-year collision of the Indian and Eurasian tectonic plates that created the Himalayan range — the most recent major mountain-building event in Earth''s history and the process responsible for Nepal''s extraordinary vertical range of habitat.',
  "CulturalImportance" = 'Nepal contains eight of the world''s 14 highest mountains, 75 per cent of the world''s climatic zones within a single country, and some of the highest concentrations of endemic plant and animal species on earth. Yet this natural wealth is largely unknown even to Nepali citizens. The Natural History Museum makes the country''s biodiversity visible and accessible, complementing the spiritual significance of the Swayambhunath complex by reminding visitors that the natural world itself — celebrated in the Buddhist tradition as the environment of all sentient beings — is in Nepal a place of exceptional richness and fragility.'
WHERE "Id" = 48;

-- ID 49: Charaudi Danda Temple
UPDATE "CulturalSites" SET
  "ShortDescription" = 'A scenic hilltop temple dedicated to Lord Shiva at Charaudi Danda above Bharatpur city in Chitwan district, offering panoramic views across the Chitwan plains, the Rapti River, and the forested hills of the Inner Terai. A popular pilgrimage site for the communities of Chitwan and a peaceful retreat from the busy tourist city below.',
  "HistoricalSignificance" = 'The temple has been a local pilgrimage site for the communities of Chitwan for several generations, associated with the Brahmin and Chhetri communities who settled the Inner Terai as the malaria eradication programme of the 1950s opened the region to permanent habitation. Before that programme, the dense forests of Chitwan were largely uninhabited by permanent settlers. The temple''s hilltop location above what has become a major regional city gives it a commanding presence in the area''s religious landscape.',
  "CulturalImportance" = 'Charaudi Danda Temple serves the growing urban community of Bharatpur — Nepal''s fourth-largest city and the headquarters of Chitwan, one of the country''s most economically dynamic districts. The temple provides a sacred counterpoint to the commercial bustle of the city below and a viewpoint that lets residents and visitors see the broader landscape of the Chitwan valley — the forests, rivers, and plains that make this region one of the most biodiverse areas of the Himalayan foothills.'
WHERE "Id" = 49;

-- ID 50: Manakamana Cable Car
UPDATE "CulturalSites" SET
  "ShortDescription" = 'Nepal''s first aerial ropeway, carrying pilgrims and visitors in glass gondolas over dramatic gorges and forested ridges to reach the Manakamana Temple at 1,302 metres above the Marsyangdi valley. The 10-minute cable car ride replaces what was historically a three-hour uphill trek. The views of the Himalayan foothills and distant snow peaks from the gondola are among the most accessible mountain panoramas in Nepal.',
  "HistoricalSignificance" = 'The Manakamana Cable Car was built by the Himalayan Cableway company with Doppelmayr Austria technology and opened in 1998 as Nepal''s first such installation. The engineering challenge of spanning the deep Marsyangdi gorge in a seismically active zone required careful design and has been validated by the structure''s performance through two major earthquakes (2011 Sikkim and 2015 Gorkha). The cable car transformed the pilgrimage economics of Manakamana, making it accessible to elderly pilgrims, families with young children, and those with limited mobility who would never have managed the original climb.',
  "CulturalImportance" = 'The Manakamana Cable Car is a vivid example of Nepal''s characteristic fusion of ancient and modern — a medieval pilgrimage tradition served by 21st-century engineering. For millions of Nepali Hindus, the goddess remains as powerful as ever regardless of how one arrives at her temple. The cable car station area has developed into a significant commercial hub, and the journey itself has become part of the pilgrimage experience rather than a mere convenience. Tourists who visit primarily for the views and the cultural experience share gondolas with deeply devoted pilgrims carrying live animals for sacrifice — a juxtaposition that captures something essential about contemporary Nepal.'
WHERE "Id" = 50;
