class RegisterUser {
  final String? userId;          // Guid from backend, optional
  final String name;
  final String email;
  final String? phone;           // optional, user can add later
  final String password;
  final String role;
  final String? profileImage;    // optional
  final DateTime? createdAt;     // generated by backend
  final DateTime? updatedAt;     // generated by backend

  RegisterUser({
    this.userId,
    required this.name,
    required this.email,
    this.phone,
    required this.password,
    required this.role,
    this.profileImage,
    this.createdAt,
    this.updatedAt,
  });

  factory RegisterUser.fromJson(Map<String, dynamic> json) {
    return RegisterUser(
      userId: json['userId'], // Guid as string
      name: json['name'] ?? '',
      email: json['email'] ?? '',
      phone: json['phone'],
      password: json['password'] ?? '',
      role: json['role'] ?? 'tourist',
      profileImage: json['profileImage'],
      createdAt: json['createdAt'] != null ? DateTime.parse(json['createdAt']) : null,
      updatedAt: json['updatedAt'] != null ? DateTime.parse(json['updatedAt']) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      "name": name,
      "email": email,
      "password": password,
      "role": role,
      "phone": phone,
      "profileImage": profileImage,
    };
  }
}